"""movies, people, streaming services, providers

Revision ID: b520f3ed1a28
Revises: 
Create Date: 2026-09-30 13:58:14.278462

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b520f3ed1a28'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.Text(), nullable=True),
    sa.Column('runtime_min', sa.Integer(), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('directors', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('top_cast', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('tmdb_popularity', sa.REAL(), nullable=True),
    sa.Column('tmdb_vote_average', sa.REAL(), nullable=True),
    sa.Column('tmdb_vote_count', sa.Integer(), nullable=True),
    sa.Column('metadata_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tmdb_id')
    )
    op.create_index('ix_movies_release_date', 'movies', ['release_date'], unique=False)
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('streaming_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('logo_path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie_providers',
    sa.Column('movie_id', sa.BigInteger(), nullable=False),
    sa.Column('region', sa.CHAR(length=2), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['streaming_services.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'region', 'service_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_providers')
    op.drop_table('streaming_services')
    op.drop_table('people')
    op.drop_index('ix_movies_release_date', table_name='movies')
    op.drop_table('movies')
    # ### end Alembic commands ###
